version: '3.7'

services:
    ignite-challenge-database-queries:
        image: postgres
        container_name: ignite-challenge-database-queries
        restart: always
        ports:
            - 5432:5432
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=docker 
            - POSTGRES_DB=queries_challenge
        volumes:
            - ./pgdata:/var/lib/postgresql/data
    app:
        build: .
        container_name: desafio03
        ports:
            - 3333:3333
        volumes:
            - .:/usr/app
        links:
            - ignite-challenge-database-queries
volumes:
    pgdata:
        driver: local